CREATE TABLE REVINFO 
  ( 
     REV BIGINT NOT NULL, 
     REVTSTMP NUMERIC(19, 0), 
     REMOTE_ADDRESS VARCHAR(255), 
     USERNAME VARCHAR(255), 
     PRIMARY KEY (REV) 
); 
  
CREATE TABLE USERS (
	ID SERIAL NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(150) NOT NULL,
	CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDDATE_DATE TIMESTAMP,
	DELETE_DATE TIMESTAMP,
	CONSTRAINT USER_PK PRIMARY KEY (ID)
);

CREATE TABLE USERS_AUD (
  	 ID SERIAL NOT NULL, 
     REV BIGSERIAL NOT NULL, 
     REVTYPE SMALLSERIAL, 
     UPDDATE_DATE TIMESTAMP,
	 DELETE_DATE TIMESTAMP,
     EMAIL VARCHAR(255), 
     NAME VARCHAR(255), 
     PASSWORD VARCHAR(255), 
     USERNAME VARCHAR(255), 
     PRIMARY KEY (ID, REV) 
);

ALTER TABLE USERS_AUD 
  ADD CONSTRAINT FK_USER_AUD_REVINFO FOREIGN KEY (REV) REFERENCES REVINFO; 